name: Playwright Test Route Coverage
on:
  workflow_dispatch: # Allow manual triggering only
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  playwright-test-route-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/e2e_coverage/
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache Yarn 4
        uses: ./.github/actions/cache-yarn

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Build app
        working-directory: ./
        run: yarn build

      - name: Make script executable
        run: chmod +x ./route-coverage-analysis.sh

      - name: Run script
        run: ./route-coverage-analysis.sh

      - name: Upload Playwright test route coverage artifact
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-test-route-coverage-report
          path: coverage/